#!/bin/bash
ORIGINAL_GATEWAY=`ip route show | grep ^default | cut -d ' ' -f 2-5`

ip route add 94.23.38.54 $ORIGINAL_GATEWAY
ip route add 0.0.0.0/1 via 10.10.10.1 dev tun0
ip route add 128.0.0.0/1 via 10.10.10.1 dev tun0
